# Generated by Django 5.1.7 on 2025-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_shipping_payment_order_productorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
